### ISSUE TITLE
Add option to hide volume control until hover over sound icon

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/app-extension-qmediaplayer#14]

**Comment by hawkeye64** [comment]
I know exactly what you mean. Will look into it.

**Comment by hawkeye64** [comment]
I've been thinking about this and this is not a good UX for mobile users. Looking for some input/ideas if you have any.

**Comment by CheyenneForbes** [comment]
Most platforms including facebook, youtube and google chrome remove the volume up/down control for mobile video and leave it to the device by having the video volume set to 100% and only use the sound icon for mute/unmute.

I believing following the same path -> show the volume level control on sound icon hover for desktop but only mute/unmute on mobile

load this video in chrome then load the developer tools and switch to mobile view (or open it on a mobile device to see)
[http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4)

**Comment by hawkeye64** [comment]
Thanks for the info. Will do. :)

**Comment by CheyenneForbes** [comment]
Would you also be able to assist me with another quasar issue? https://github.com/quasarframework/quasar/issues/4202

**Comment by hawkeye64** [comment]
I don't know anything about `css-loader`. Also, look up the `.pre()` functuon on rules to see if you need that.

**Comment by hawkeye64** [comment]
For now, I have added a property to `hide-volume-slider` - hoping that is good enough for now.
Will be in next release.

**Comment by hawkeye64** [comment]
It's really 'hide-volume-slider'
