### ISSUE TITLE
Subtitles should be pushed higher when mouse hover reveals the controls instead of being covered by it

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/app-extension-qmediaplayer#15]

**Comment by hawkeye64** [comment]
Thank you for bringing this to our attention.
Currently, the subtitles are managed by the underlying HTML5 HTMLMediaElement component. Unless it's decided to manage the subtitles ourselves (which would require mounds of work and bloat QMediaPlayer), there is nothing that can be done about this. Sorry.
