### ISSUE TITLE
Broken link for the "Sintel" video in Demo project

### ISSUE THREAD

**Issue by invyspirit** [quasarframework/app-extension-qmediaplayer#16]
The second video ("Sintel") appears to have a broken link attached to it. The link that seems to have issue is: [https://peach.themazzone.com/durian/movies/sintel-2048-surround.mp4](https://peach.themazzone.com/durian/movies/sintel-2048-surround.mp4). Tried on Safari (12.1.1), Chrome (74.0.3729.169), Firefox (67.0.1).

Error example from FF: `HTTP load failed with status 404. Load of media resource https://peach.themazzone.com/durian/movies/sintel-2048-surround.mp4 failed.`

Error example from Chrome: `GET https://peach.themazzone.com/durian/movies/sintel-2048-surround.mp4 404 (Not Found)`

Error example from Safari: `Failed to load resource: the server responded with a status of 404 (Not Found)` (pointing to the same media file URL).

**Comment by hawkeye64** [comment]
```
Not Found
The requested URL /durian/movies/sintel-2048-surround.mp4 was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```
That mirror seems to have an issue. Likely they moved the link.
Yep, new link here: http://www.peach.themazzone.com/durian/movies/sintel-2048-surround.mp4
It's no longer being served from a secure server. :(

Fixed in the demo: https://quasarframework.github.io/app-extension-qmediaplayer/demo
