### ISSUE TITLE
Browser warning for parsing height/width of loader (spinner)

### ISSUE THREAD

**Issue by invyspirit** [quasarframework/app-extension-qmediaplayer#17]
Issue does not seem to affect performance or appearance.
Warning appears in Safari (12.1.1) and Firefox (67.0.1).
Chrome (74.0.3729.169) is fine however.

Warning from FF: `Unexpected value 3rem parsing width attribute. Unexpected value 3rem parsing height attribute.`

Error from Safari: `Error: Invalid value for <svg> attribute height="3rem" Error: Invalid value for <svg> attribute width="3rem"`

Both warnings above refer to https://quasarframework.github.io/app-extension-qmediaplayer/js/vendor.f38fe7b9.js and inspecting for the element that the above mentioned height and width are being applied to results in `q-spinner` element `<svg width="3rem" height="3rem" viewBox="25 25 50 50" class="q-spinner q-spinner-mat">...</svg>`.

Once again, does not seem to affect performance and appearance, spinner box rendered size is reasonable and computes to 48*48px on my screen resolution (2560*1600px).

Same issue appears in my project. No additional styling is used.
`<q-media-player
  type="video"
  :sources="video.sources"
  :poster="video.poster"
  :autoplay="true"
  :show-big-play-button="false"
  :no-controls="true"
  :muted="true"
/>`

**Comment by hawkeye64** [comment]
Interesting that Safari has issues with rem on svg elements.
After some research, I see that Chrome (and webkit dirivities) support rem on svg only.
I'll make adjustments this weekend. Thanks for bring this to my attention.

**Comment by hawkeye64** [comment]
I am a bit perplexed about this one. Quasar is using rem for QIcon
```css
.q-icon
  line-height 1
  width 1em
  height 1em
  letter-spacing normal
  text-transform none
  white-space nowrap
  word-wrap normal
  direction ltr
  text-align center
  position relative
  font-display block 
```
Do you know if an icon or spinner has the same issue?
https://quasar.dev/vue-components/icon
https://quasar.dev/vue-components/spinners

I also get this in Chrome dev tools when viewing Quasar spinners page:
![image](https://user-images.githubusercontent.com/10262924/59354661-bfcea800-8ce2-11e9-9fe2-1204c032d5f2.png)

**Comment by invyspirit** [comment]
Just checked it. The conde I used:
```
    <q-icon name="fas fa-users" />
    <q-icon name="fas fa-users" style="font-size: 3em" />
    <q-icon name="fas fa-users" style="font-size: 3rem" />
    <q-icon name="fas fa-users" size="3em" />
    <q-icon name="fas fa-users" size="3rem" />
    <q-spinner color="secondary" />
    <q-spinner color="secondary" size="3em" />
    <q-spinner color="secondary" size="3rem" />
```

Chrome is fine with all of these - no warnings.
One thing to notice, Chrome (or Quasar) converts `size` in `q-icon` to `style="font-size:"`. So in Chrome inspector icons 2 and 4, and 3 and 5 are exact same. They do preserve units though, so 2 and 4 are `em`, and 3 and 5 are `rem`. Display-wise icon in each "group" are a bit different, but that's due to difference between `em` and `rem` I think.

Firefox and Safari are a different story though. Icons are fine. No warnings, display-wise and if inspected, behaviour is exact same as in Chrome. Spinners are different. So:
1. If I inspect them - in all three browsers they are the same - `width:` `1em` `3em` `3rem` respectively.
2. Spinner with `size="3rem"` makes browser throw the exact same warnings as described in this issue post.
3. Display-wise. Safari renders everything inline, so that the last spinner is "squished" down to the same size as the largest element in its line (3em spinner). Firefox, on the other hand, throws the last spinner on a new line and makes it occupy 100% width of the page (`<html>`, not `<q-page>`). So basically occupy anything, but preserve aspect ratio (a square essentially).

I suggest the "quick-fix" would be to generate spinners in `q-media-player` with `em`-based sizing and not `rem`.

**Comment by hawkeye64** [comment]
You think 3em wouild suffice?

**Comment by invyspirit** [comment]
Well `QSpinner` lets you set its size to `rem` (as per Quasar docs), but it defaults to `em` if no size is specified. So I think sticking with main Quasar library approach and defaulting to sizes in `em` will be sufficient.

On that note, it'd be great to have a `:spinner-size="CSS_units_including_unit_name"` property for `q-media-player`. However there is already a slot to replace default spinner, so it's up to your library design preference. For me having a slot for spinner is enough if I would need to change it.

**Comment by hawkeye64** [comment]
Thanks - I prefer that design as well.

**Comment by hawkeye64** [comment]
Fixed in beta.16
