### ISSUE TITLE
Browser is defaulting to the first source in 'sources', irrespective of support for video type

### ISSUE THREAD

**Issue by invyspirit** [quasarframework/app-extension-qmediaplayer#18]
Stumbled upon the issue when testing in Safari (12.1.1).

I have two video sources, that I'm testing with (pulled from [QParallax](https://quasar.dev/vue-components/parallax#Usage)). When rendering, browser is supposed to look at sources provided (starting from the first one) and resolve to the first one that it supports ([MDN Element Video](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)). Given limited support for `webm` in Safari, it resolves to `video/mp4` over `video/webm`.

However, when implemented using QMediaPlayer, the created HTML `video` tag seems to implicitly set `src` attribute to the first `source` provided (see example below). This seems to force Safari to use this source, whether it supports it or not (bypassing the check for video type support). This resolves in Safari trying to playback `webm` source, should it be the first one mentioned in the list of `sources`.

Code that I'm using in my project:
```
<q-media-player
  type="video"
  :sources="video.sources"
  :poster="video.poster"
  :autoplay="true"
  :show-big-play-button="false"
  :no-controls="true"
  :muted="true"
/>
...
video: {
  poster: 'https://cdn.quasar.dev/img/polina.jpg',
  sources: [
    {
      src: 'https://cdn.quasar.dev/img/polina.webm',
      type: 'video/webm'
    },
    {
      src: 'https://cdn.quasar.dev/img/polina.mp4',
      type: 'video/mp4'
    }
  ]
}
```
Code that is being generated for my web page is:
```
<video
  poster="https://cdn.quasar.dev/img/polina.jpg" 
  preload="metadata" 
  class="q-media--player" 
  src="https://cdn.quasar.dev/img/polina.webm"
>
  <p>To view this video please enable JavaScript and/or consider upgrading to a browser that supports HTML5 video.</p>
  <source src="https://cdn.quasar.dev/img/polina.webm" type="video/webm">
  <source src="https://cdn.quasar.dev/img/polina.mp4" type="video/mp4">
</video>
```
Please notice how `video` tag gets its `src` attribute set to `webm` source.
Firefox (67.0.1) and Chrome (74.0.3729.169) work fine.
Safari, given its limited support for `webm`, ends up with endless spinner being displayed on top of a crossed-out play button (default apple style), and never resolves to play `mp4` source provided.

However, should I change the order of provided sources (so that `mp4` goes first, followed by `webm`) - `src` attribute changes to `mp4` source and Safari plays it just fine (just like in QParallax example mentioned above). But that's an unwanted workaround since I'd like `webm` to be my primary video source.

QParallax generated HTML code example below:
```
<div class="q-parallax__media absolute-full">
  <video 
    width="720" 
    height="440" 
    poster="https://cdn.quasar.dev/img/polina.jpg" 
    autoplay="autoplay" 
    loop="loop" 
    muted="muted" 
    style="transform: translate3d(-50%, 115px, 0px);"
>
    <source type="video/webm" src="https://cdn.quasar.dev/img/polina.webm">
    <source type="video/mp4" src="https://cdn.quasar.dev/img/polina.mp4">
  </video>
</div>
```

I suggest the fix would be to not set `src` attribute inside `video` tag at all. I tested creating such code "by hand" and it results in the expected behaviour (Chrome and FF grab the `webm` source, which is the first one mentioned, and Safari goes to `mp4`)

**Comment by hawkeye64** [comment]
I'll investigate this on the weekend. Thanks for bring it to my attention.

**Comment by hawkeye64** [comment]
So, here is some interesting news:
```
<video poster="statics/media/TearsOfSteel/TearsOfSteel.jpeg" preload="metadata" class="q-media--player" src="https://ftp.nluug.nl/pub/graphics/blender/demo/movies/ToS/ToS-4k-1920.mov">
  <p>To view this video please enable JavaScript and/or consider upgrading to a browser that supports HTML5 video.</p>
  <source src="https://ftp.nluug.nl/pub/graphics/blender/demo/movies/ToS/ToS-4k-1920.mov" type="video/mp4">
  <track kind="subtitles" label="English" src="statics/media/TearsOfSteel/TOS-en.vtt" srclang="en">
  <track kind="subtitles" label="German" src="statics/media/TearsOfSteel/TOS-de.vtt" srclang="de">
  <track kind="subtitles" label="Spanish" src="statics/media/TearsOfSteel/TOS-es.vtt" srclang="es">
  <track kind="subtitles" label="French" src="statics/media/TearsOfSteel/TOS-fr-Goofy.vtt" srclang="fr">
  <track kind="subtitles" label="Italian" src="statics/media/TearsOfSteel/TOS-it.vtt" srclang="it">
  <track kind="subtitles" label="Dutch" src="statics/media/TearsOfSteel/TOS-nl.vtt" srclang="nl">
</video>
```
The above is how it looks in my browser. Notice this line:
` src="https://ftp.nluug.nl/pub/graphics/blender/demo/movies/ToS/ToS-4k-1920.mov"`

I don't put that there. I write out the <source> tags inside the video element and it picks one and writes that attribute to itself.

Here is the code:
```
      __renderVideo (h) {
        return h('video', {
          ref: 'media',
          staticClass: 'q-media--player',
          class: this.contentClass,
          style: this.contentStyle,
          attrs: {
            poster: this.poster,
            preload: this.preload,
            playsinline: this.inline,
            loop: this.loop
          }
        }, [
          this.isVideo && h('p', this.lang.mediaPlayer.oldBrowserVideo, slot(this, 'oldbrowser'))
        ])
      },
```
and sources:
```
      __renderSources (h) {
        return this.sources.map((source) => {
          return h('source', {
            attrs: {
              key: source.src + ':' + source.type,
              src: source.src,
              type: source.type
            }
          })
        })
      },
```

**Comment by invyspirit** [comment]
This is indeed interesting. I am not sure these issues are connected and I will have to google deeper, but I had the following experience some time ago:
1. I had an empty `table` tag in my HTML
2. With JS:
```
  let row = document.createElement("tr")
  let cell = document.createElement("td")
  row.appendChild(cell)
  table.appendChild(row)
```
3. What browser recreated for me was the table that I wanted, but with `thead` and `tbody` tags inside as well.

I guess it's just browsers trying to be more forgiving, since, if I'm not mistaken, having at least a `tbody` tag is required in a table. I don't think having an `src` is obligatory in our case, but maybe this is what's happening here.

I'll trying to research this question in more detail during the weekend.

**Comment by hawkeye64** [comment]
Yes, the browser will try to correct inconsistencies when dynamically. This is why you can have rehydration errors with SSR, especially with table elements, if not done correctly.

**Comment by hawkeye64** [comment]
Going to close this for now as I think this is a non-issue for QMediaPlayer.
