### ISSUE TITLE
Improvement proposal: add 'object-fit' attribute

### ISSUE THREAD

**Issue by invyspirit** [quasarframework/app-extension-qmediaplayer#19]
It would be great to have an ability to set `object-fit`-like property to `q-media-player`.

Somewhat straightforward way (tested in browser, but not sure of compatibility) would be to set `div.q-media style="height: 100%"` to make it occupy the entire parent container and then `video style="object-fit:{{ property }}`.

The idea is to be able to do something like this:
```
<q-media-player
  :sources="video.sources"
  :object-fit="video.fit"
>
...
video: {
  sources: [...],
  fit: "cover"
}
```

**Comment by hawkeye64** [comment]
One issue with this is that the HTML5 player needs a width and height in order to work properly. I might be able to get the computedheight and computedWidth from the parent div and use that. I'll investigate this weekend.

**Comment by hawkeye64** [comment]
I did add, in the lastest, 2 new properties you can play with: `content-class` and `content-style`. These may help a bit.

**Comment by hawkeye64** [comment]
Is this sufficient? Let me know.

**Comment by hawkeye64** [comment]
Closing for now.
