### ISSUE TITLE
feat: add 'loop' attribute

### ISSUE THREAD

**Issue by invyspirit** [quasarframework/app-extension-qmediaplayer#20]
It'd be nice to have simple `:loop="true"` property. It's a native property of HTML `video` tag. Just like it already works with `:muted` and `:autoplay`.

**Comment by invyspirit** [comment]
As far as I understand, current method of looping the video would be to `togglePlay()` on `@ended` event. I have not yet thoroughly debugged it, but it seems that in Chrome and Safari the video would pause after a certain delay if the browser window is not active. Should this be by design, it seems like a useful feature to reduce system resources usage, but having some control over it appears to be necessary in certain scenarios.

A workaround would be to invoke the same method on `@paused`, but it just feels clumsy, especially knowing that HTML `video` tag supports `loop` property by default.

**Comment by hawkeye64** [comment]
Agreed. Will take a look at it this weekend.

**Comment by hawkeye64** [comment]
Added in v1.0.0-beta.15
