### ISSUE TITLE
feat: add 'playsinline' attribute

### ISSUE THREAD

**Issue by invyspirit** [quasarframework/app-extension-qmediaplayer#21]
Despite several improvements in the past several years Safari on iOS is still somewhat restrictive in terms of displaying a video to a user. Especially when it comes to playing videos "inline" as opposed to going fullscreen.

For example to make a video `autoplay` in the background in iOS Safari a developer would need to include `playsinline` attribute inside a `video` tag. That's on top of usual `autoplay` and `muted`. For this matter, it'd be great to have the ability to set `:playsinline: "true"` inside `q-media-player`.

Thank you

**Comment by hawkeye64** [comment]
Thanks for bring this up. I agree.
Keep on going with the good suggestions, too :)

**Comment by hawkeye64** [comment]
added in v1.0.0-beta.15
