### ISSUE TITLE
The player detects the time track clicks as if I am clicking on the big play button

### ISSUE THREAD

**Issue by Bogatinovski** [quasarframework/app-extension-qmediaplayer#23]
I have just installed this plugin and whenever I click on the time track to change the current time and the video player pause or unpause the video depending on the current state. If it is playing the video and I click on the time track then the video is paused. If the video is paused and then I click on the time track then the video is unpaused. Basically the player detects the time track clicks as if I am clicking on the big play button.
Here is how I initialize the player:

```
       <q-media-player
            v-if="video !== null"
            type="video"
            background-color="black"
            :autoplay="false"
            class="video-player"
            :dense="true"
            :show-big-play-button="true"
            :sources="video.sources"
            :poster="video.poster"
            @ended="onEnded"
          >
          </q-media-player>
```
.......
```
      this.video = {
          label: stream.Title,
          poster: stream.Poster,
          sources: [
            {
              src: response.data.Url,
              type: 'video/mp4'
            }
          ]
        }
```

**Comment by hawkeye64** [comment]
Thanks for reporting.

**Comment by hawkeye64** [comment]
I know exactly what is happening. I will be out all weekend, so will try to get this done early next week.

**Comment by Bogatinovski** [comment]
Thank you so much, it will be very much appreciated!

**Comment by hawkeye64** [comment]
Sorry, it's taken so long. I totally forgot about this. Will try to have a fix in for today.

**Comment by hawkeye64** [comment]
@Bogatinovski ok, so I tested and cannot replicate what I thought the issue was, so maybe I need some clarification. When I click on the time track, it goes to that position in the movie, but it does not start playing for me. The Big Play Button is still available.
![image](https://user-images.githubusercontent.com/10262924/60984788-82693480-a2f9-11e9-918a-0282daa75a9a.png)

**Comment by Bogatinovski** [comment]
For some reason it is working correctly now. I really don't remember changing anything so I have no idea how to reproduce the issue that was happening. Perhaps we should close the issue for now and reopen it in the future if it happens again.

**Comment by hawkeye64** [comment]
Sounds good. Probably was a fix in Quasar that caused this issue to be fixed.
