### ISSUE TITLE
[FEAT]: Provide facility to change audio/video source directly

### ISSUE THREAD

**Issue by Bogatinovski** [quasarframework/app-extension-qmediaplayer#24]
It will be very helpful if the player supported changing of video quality so that the users can choose if they want to play 1080p or 720p video quality. Changing the video quality boils down to changing the video src. I guess I can actually implement this functionality myself by placing buttons somewhere outside of the video player and respond to click events to change the video src. But it would be much better UX if these buttons were embeded inside the player itself so that is more native experience.

**Comment by hawkeye64** [comment]
I opted for the ability to change the video.src directly via a new propery `source`. That way, it provides the best way to facilitate all devs using the component.
`:source='url-to-my-source'`
fixed in beta.18
