### ISSUE TITLE
Will you support streaming videos of type HLS or DASH ?

### ISSUE THREAD

**Issue by Bogatinovski** [quasarframework/app-extension-qmediaplayer#25]

**Comment by hawkeye64** [comment]
Possibly, in the future. QMediaPlayer is a wrapper for MediaElement (ie: video and audio tags). It doesn't support HLS or DASH and owuld have to be custom written in to do so.

**Comment by hawkeye64** [comment]
Closing this for now.

**Comment by francoism90** [comment]
It seems ME does support HLS/DASH nowadays, is this correct?

**Comment by hawkeye64** [comment]
@francoism90 No idea. I haven't had time to keep up with it.
