### ISSUE TITLE
Icons set for player controls

### ISSUE THREAD

**Issue by digiproductmarketer** [quasarframework/app-extension-qmediaplayer#26]
QMediaPlayer appears to have a dependancy on 'material-icons' which does not appear to be documented.

If you only have 'fontawesome-v5' in the extras section of quasar.config.js then the video controls get messed up because the required icons are no longer available.

Adding 'material-icons' to the extras of quasar.config.js resolves this.

**Comment by hawkeye64** [comment]
@digiproductmarketer 
This is the code that gets run in beforeMount() function:
```
      __setupIcons () {
        let iconName = this.$q.iconSet.name || 'material-icons'
        let iconSet
        try {
          iconSet = require(`./iconSet/${iconName}`)
        } catch (e) {}
        iconSet && (this.iconSet['mediaPlayer'] = { ...iconSet.default.mediaPlayer })
      },
```
You can see it will load an icon set based on Quasar's icon set name, which, if not valid, falls back to 'material-icons'. If you are not adding 'material-icon's, then you have to set the icon set to use in `quasar.conf.js`:
```
framework: {
  iconSet: 'fontawesome-v5'
}
```
There are some examples coming (hopefully today), which demonstrate this.
