### ISSUE TITLE
Example source on main page of docs is incorrect

### ISSUE THREAD

**Issue by digiproductmarketer** [quasarframework/app-extension-qmediaplayer#27]
the example source in the main page of the docs is incorrect ... 

it's missing the [videoindex] in the :sources, post, and tracks

It's NOT 
```
      :sources="video.sources"
      :poster="video.poster"
```

It SHOULD BE
```
      :sources="video[videoIndex].sources"
      :poster="video[videoIndex].poster"
```

and  videoIndex is missing from he example data section
```
      videoIndex: 0,
```

Works fine then

**Comment by digiproductmarketer** [comment]
Perhaps an extra simple example might be useful ... 

Just a poster and a video ... both online resources ... would be useful

Then folks can just copy, paste, and have a working example as a starting point ...

No need to worry about missing resources, incorrect setup ... just a straight confidence boost ...

**Comment by hawkeye64** [comment]
Agree, I need better examples. However, the code on the docs should be correct. There is onlly one `video.sources`, the `video` is not an array.

However, it is in the demo example, so it can switch between videos.

**Comment by hawkeye64** [comment]
I take it back. `video` **IS** an array. Thanks for findiung this.

**Comment by hawkeye64** [comment]
Fixed and live in docs.
