### ISSUE TITLE
Settings menu doesn't open while in fullscreen

### ISSUE THREAD

**Issue by Blaconix** [quasarframework/app-extension-qmediaplayer#45]
As we can see in the demo [`here`](https://quasarframework.github.io/app-extension-qmediaplayer/demo) the settings menu doesn't open while the player is in fullscreen and trying to change it using for example:

`<template v-slot:settings-menu>
  <q-btn label='Test' />
</template>`

Doesn't have any effect.

**Comment by hawkeye64** [comment]
Thanks for reporting. This is probably a z-index issue. I will investigate.

**Comment by hawkeye64** [comment]
I put the other part here: https://github.com/quasarframework/app-extension-qmediaplayer/issues/50

as each problem should be reported in its own issue.

**Comment by hawkeye64** [comment]
Fixed in 1.0.4
