### ISSUE TITLE
Reactive prop for audio source

### ISSUE THREAD

**Issue by PavarinE** [quasarframework/app-extension-qmediaplayer#47]
I’m using a q-media component with a :source prop that comes initially as a string that comes from the data() initial data of my component.

When certain events occurs on my component, I’m trying (in a method) to change the source of the q-media components like:

```
any_method() {
  this.cur_audio_url = "another_audio_url"
}
```

But the audio source is not changing. Is the source prop of q-media component intended to be reactive? Is that anything I can do to achiev such a thing?

```
<q-media-player
	  ref="audio_player"
	  type="audio"
	  background-color="black"
	  radius="1rem"
	  track-language="English"
	  :autoplay="true"
	  :source="cur_audio_url"
	  @loaded="audio_loaded"
	  @ready="audio_ready"
>
```

**Comment by hawkeye64** [comment]
Yes, it writes it in directly. Can you look in browser dev tools and see if it changed?

**Comment by PavarinE** [comment]
@hawkeye64 In VueDevTools I can see that the "source" property in the q-media component is indeed changing reactively, but looking in the native html tag (<video> tag) I can see that the "src" property is not changing at all. I think that there is some reload() or load() methods that must be called from the <video> html tag in order to acomplish this... sry for bad english

**Comment by hawkeye64** [comment]
yes, you are right. Sorry, I didn't take time to look into this for the release I did. You can see in the interactive example that it switches out `sources` and does that, but it's not done for `source` (just pointing this out as a reminder for myself).

**Comment by hawkeye64** [comment]
will be fixed in v1.0.10 (next release)

**Comment by hawkeye64** [comment]
@PavarinE Can you test and make sure this is no longer an issue for you? Thanks.

**Comment by hawkeye64** [comment]
@PavarinE Any traction on this?

**Comment by PavarinE** [comment]
@hawkeye64 Sorry for the delay, is that I was working on another project. I'd tested and aparently it worked for me, but I'll make some more solid tests on it until friday, so I can give a more concise feedback

**Comment by hawkeye64** [comment]
@PavarinE Thanks

**Comment by PavarinE** [comment]
@hawkeye64 Confirming, we 're good at this. Worked pretty well for me! Apreciate your work

**Comment by hawkeye64** [comment]
@PavarinE Awesome to hear that. Closing this issue then. Thanks! :heart:
