### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/app-extension-qmediaplayer#48]
Would be great if IE11 could also be supported. 
There is an error objectDOMexception when the page is loaded 

- my project:
```html
<template>
  <div class="column items-center q-pa-md">
    <div class="row" style="height:400px;">
      <q-media-player
        :sources="sources"
        background-color="white"
        type="video">
      </q-media-player>
    </div>
  </div>
</template>
```
```js
 data() {
      return {
        sources: [
          {
            src: "./data/test.m4v",
            type: "video/m4v"
          },
          {
            src: "./data/test.mp4",
            type: "video/mp4"
          }]
      };
    }
```
![image](https://user-images.githubusercontent.com/37825539/61928710-9a87b780-af79-11e9-8e6b-e55ec32ea06c.png)

- [qmediaplayer - exapmles](https://quasarframework.github.io/app-extension-qmediaplayer/docs).
![image](https://user-images.githubusercontent.com/37825539/61928704-90fe4f80-af79-11e9-8d3b-d6eaf70e305c.png)
![image](https://user-images.githubusercontent.com/37825539/61928796-db7fcc00-af79-11e9-9c60-2480e4139007.png)

**Comment by hawkeye64** [comment]
Thanks for reporting this. :heart: I wish I had IE11 to test with. The UI looks a bit messed up. Not sure what I can do here, but I'll see if I can come up with something.

**Comment by hawkeye64** [comment]
Just dicovered that IE11 does not support `classList` functionality. This is used when going in and coming out of fullscreen.
If you wouldn't mind trying some polyfill for it and letting me know how it goes, that would be appreciated.

**Comment by m0jimo** [comment]
- I tried to add a polyfill for classList from [Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) site as ```import "classListPolyfill"``` to the various places: QMediaPlayer or import it as ```<script src="./assets/classListPolyfill.js"></script>``` to index.templates.html file. It had a problem with function .remove. 
- I tried to comment all (6) classList events. Error remained the same (without polyfill)
- I also tried to add [binding](https://stackoverflow.com/questions/1695376/msie-and-addeventlistener-problem-in-javascript) for attaching events. No difference.
- I tried to install with yarn your suggested polyfill but I don't know if it needs additional configuration. It was added to yarn.lock but after restart IE was at the same stage.

At this stage I don't know what else could be a problem.

**Comment by hawkeye64** [comment]
I will try to get rid of the code using `classList` and re-code it in a different way. Give me a couple of days as I am slammed at work.

**Comment by m0jimo** [comment]
If it was a problem of classList then it would work after commenting those lines but it had no effect. There must be another thing before reaching classList functions. It is a Vue warning so something when it tries to mount the player.

I have a another HTML5 video player generated from Authoring SW Opus Pro (DigitalWorkshop) and it plays. So I can confirm that IE11 and local security configuration should be OK. When you have more time I can upload to my git example code. You might get better idea.

I’m not in hurry, so there is no rush with fixing it now. I’d like to help you but I don’t know what I should try the next. If you have idea let me know and I can try it.

**Comment by hawkeye64** [comment]
I will try to do this by next weekend (new release). If I haven't, give me a nudge. Thanks.

**Comment by hawkeye64** [comment]
@m0jimo Sorry, I can't find anything that will help me fix this. You're going to have to try and track down more info for me. :(

**Comment by smakinson** [comment]
Was checking out the player and happen to see this issue. I am curious about potentially checking this out instead of my custom use of Howler, but ie11 is a must for me still. I'm in no hurry though. Anyway, I thought I'd share how I test in ie11 incase its helpful. I use the virtualbox VM from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by hawkeye64** [comment]
@smakinson I am currently actively working on this and may have a fix.

**Comment by hawkeye64** [comment]
will be fixed in v1.0.10. Let me know if it is still an issue for you.

**Comment by hawkeye64** [comment]
@m0jimo Let me know when you have tested so this can be closed.

**Comment by smakinson** [comment]
@hawkeye64 Do you know if anyone has tested in cordova say back to android 4.4.4 and iOS to some extent?

**Comment by hawkeye64** [comment]
Sorry, I haven't done cordova so wouldn't know. :(

**Comment by m0jimo** [comment]
Sorry, but the result is still the same with the latest demo.
![image](https://user-images.githubusercontent.com/37825539/63571355-3eb44c80-c580-11e9-849c-108803f6a14f.png)

**Comment by hawkeye64** [comment]
Can you confirm Edge does work? And ie11 is still an issue. Crud. It doesn't give very good reasons as to why, which makes it more difficult.
