### ISSUE TITLE
在EDGE、IE浏览器上报错误

### ISSUE THREAD

**Issue by zhangzongshan** [quasarframework/app-extension-qmediaplayer#5]
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
QMediaPlayer.js (509,44)

**Comment by hawkeye64** [comment]
Just to be clear, unless I am mistaken, you have changed the language that Quasar is using and this caused an error in QMediaPlayer?

**Comment by hawkeye64** [comment]
I'm closing this issue because I have no received further input. If you feel this is incorrect, please re-open with details. Thanks.
