### ISSUE TITLE
setVolume doesn't work?

### ISSUE THREAD

**Issue by dev-steverob** [quasarframework/app-extension-qmediaplayer#52]
https://github.com/quasarframework/app-extension-qmediaplayer/blob/397d91d133b02e3b911bed10433acc7666224368/src/component/QMediaPlayer.js#L551-L555

The volume doesn't change when using the function and looking at the code it will only change the volume if it's set to 100?

**Comment by hawkeye64** [comment]
Well, that's embarassing. :(
Thanks for this. Will be fixed in v1.0.5
