### ISSUE TITLE
Check play() promise

### ISSUE THREAD

**Issue by dev-steverob** [quasarframework/app-extension-qmediaplayer#54]
I'm running the code to play audio on load, some browsers don't support this. When play fails the play button still changes to the pause button and users have to click the pause button and then play again to start the stream. Could you use the $media.play().then(-----) to set the playing status so if it fails the play button remains?

**Comment by dev-steverob** [comment]
https://github.com/quasarframework/app-extension-qmediaplayer/blob/305a33e80d03e66a7275412e09d0d6f084096d28/src/component/QMediaPlayer.js#L485-L497

` 
togglePlay () {
        if (this.$media && this.state.playReady) {
          if (!this.state.playing) {
            this.state.showBigPlayButton = false
            this.$media.play().then(() => {
                this.state.playing = !this.state.playing
            })
            this.__mouseLeaveVideo()
          } else {
            this.$media.pause()
            this.state.showBigPlayButton = true
          }
        }
      },
`

**Comment by dev-steverob** [comment]
> 
      togglePlay() {
        if (this.$media && this.state.playReady) {
          if (!this.state.playing) {
            this.state.showBigPlayButton = false
            this.$media.play().then(() => {
              this.state.showBigPlayButton = false
              this.state.playing = true
            })
            this.__mouseLeaveVideo()
          } else {
            this.$media.pause().then(() => {
              this.state.showBigPlayButton = true
              this.state.playing = false
            })
          }
        }
      },

**Comment by hawkeye64** [comment]
Thanks for the comments. Are you sure the browser returns a Promise when calling the `play()` method? I can't find anywhere that mentions this. Can you find a reference?

**Comment by dev-steverob** [comment]
Yes as I use it often. I got the code above wrong though as the pause() function doesn't return a promise.

[https://developers.google.com/web/updates/2016/03/play-returns-promise](https://developers.google.com/web/updates/2016/03/play-returns-promise)

**Comment by hawkeye64** [comment]
k, I will try to get it into the next release. I need to verify the validity first.

**Comment by hawkeye64** [comment]
will be in v1.0.7
