### ISSUE TITLE
[docs] - additional information

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/app-extension-qmediaplayer#55]
Alternative to ```@mediaPlayer()``` event which returns a native HTML5 video object can be access to a native object via ref:
```
this.$refs.qmp.$media
```
qmediaplayer methods can be accessed e.g.:
```
this.$refs.qmp.togglePlay();
```
If you need to use a pause instead of ```togglePlay``` you can call native method ```pause()```:
```
this.$refs.qmp.$media.pause();
```

I promised some time ago to publish a few examples which I miss in the docs but on the other hand every Vue user should be familiar with methods, events and refs (or at least from Quasar docs).

**Comment by hawkeye64** [comment]
I'll add some more info to the docs about accessing via a ref like this

**Comment by hawkeye64** [comment]
will be in v1.0.7
