### ISSUE TITLE
[docs] - Vue slots names

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/app-extension-qmediaplayer#56]
Slot has to be named in camelCase format otherwise it is not detected.
```
<!-- OK -->
<template v-slot:bigPlayButton>
```
```
<!-- doesn't work -->
<template v-slot:big-play-button>
```

**Comment by m0jimo** [comment]
If I use a bigPlayButton then original big play button stays there.
![image](https://user-images.githubusercontent.com/37825539/63079062-b14c7900-bf3d-11e9-8b25-94d66f119542.png)

If I hide a big button than my slot is not visible either.

**Comment by m0jimo** [comment]
How to align object to the center of the video?
```html
  <template v-slot:bigPlayButton>
                <q-btn @click="start"
                       color="brand"
                       icon="play_arrow" size="64px"
                       v-if="getProgressStatus() === 'start'">start
                </q-btn>
          </template>
```
button is sized to 64px to see how it is aligned.
![image](https://user-images.githubusercontent.com/37825539/63079781-9e3aa880-bf3f-11e9-9089-c58a16a56ac9.png)

**Comment by hawkeye64** [comment]
hmmm, that's interesting to note about camelcase. I am sure Quasar is doing it the same way I am. I'll have to check.

**Comment by realtimeappsolutions** [comment]
I just came here and discovered this issue and it helped me ... as my slot template was not displaying until I changed to v-slot:bigPlayButton adter seeing this issue.

**Comment by hawkeye64** [comment]
Hey guys, can you keep different issues in their own issue thread, otherwise it get confusing. Working on documenting the slot names properly right now. Will be available in next release.
v1.0.6
