### ISSUE TITLE
Big Play Button colour

### ISSUE THREAD

**Issue by realtimeappsolutions** [quasarframework/app-extension-qmediaplayer#57]
Would be nice to have ability to set the colour of the Big Play Button in a similar way to how the colour of the controls can be set.

**Comment by realtimeappsolutions** [comment]
I was able to get a workaround by changing the color via the border-color of q-media--big-button in the STYLE section, and using the slot ... but that introduced other issues.

**Comment by hawkeye64** [comment]
Fixed in v1.0.6

**Comment by hawkeye64** [comment]
You know, you shouldn't close until it's released and you've tested... ;)
