### ISSUE TITLE
Using img in BigPlayButton stops click

### ISSUE THREAD

**Issue by realtimeappsolutions** [quasarframework/app-extension-qmediaplayer#59]
If you use the slot for BigPlayButton, and click on the IMG rather than the rest of the video, the video will not start, and once the video is playing even though the IMG is not displayed, if you click on it's "position" the click does not stop the video.

**Comment by hawkeye64** [comment]
Yes, if you use a slot, then you are replacing the UI and functionality. You need to set up a $refs for the media player. Then handle your button click in the slot. Then call the appropriate methods for QMediaplayer (start, stop, etc).
