### ISSUE TITLE
如何支持rtmp 或 hls

### ISSUE THREAD

**Issue by zhangzongshan** [quasarframework/app-extension-qmediaplayer#6]
我需要使用 rtmp 或 hls 视频源，但好像不支持

**Comment by hawkeye64** [comment]
Unfortunately, the HTML5 does not natively support RTMP. There ways around this. For instance, you can use VLC or FFMPEG to capture the live stream and convert to a format used by HTML5 video player (ogg format).

Here's a couple of links you can look into:
https://stackoverflow.com/questions/1735933/streaming-via-rtsp-or-rtp-in-html5
https://stackoverflow.com/questions/5858936/html5-live-streaming
