### ISSUE TITLE
IE11 - remaining time position

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/app-extension-qmediaplayer#69]
IE11 has a problem with alignment of the remaining time:
![image](https://user-images.githubusercontent.com/37825539/63774214-0e044800-c8dd-11e9-80c6-f3523c5613b6.png)

**Comment by hawkeye64** [comment]
top-left instead of bottom-right? Weird.
I'll look into it when I can. Thanks for reporting. :heart:

**Comment by hawkeye64** [comment]
wait, it's all messed up, period. :(
Should be like this:
![image](https://user-images.githubusercontent.com/10262924/64209031-be81c700-ce5c-11e9-9ad6-0b24126b0ecd.png)

**Comment by m0jimo** [comment]
I quickly tried to check where the problem is. There is a width set to 100%. After removing it it looks good also in Chrome but I haven't had time to test it properly after making a change in source code - only web inspector in IE.
![image](https://user-images.githubusercontent.com/37825539/64264289-5650e500-cf31-11e9-8b16-ffd921d37eaa.png)

**Comment by hawkeye64** [comment]
Let's run with it and see how it goes. I tested with Edge and Chrome as well.
Fix will be in v1.0.12

**Comment by m0jimo** [comment]
It looks good, now in IE11. 
![image](https://user-images.githubusercontent.com/37825539/64315295-ea629100-cfb1-11e9-8884-0d38197dfd47.png)

**Comment by hawkeye64** [comment]
Thanks for the feedback. :heart:
