### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/app-extension-qmediaplayer#71]
After upgrading to v12 there is a dependency problem problem when ```dev``` or ```build``` solution.
![image](https://user-images.githubusercontent.com/37825539/64335024-2f9ab900-cfda-11e9-874a-fe69b811034c.png)

After reverting back to v11 it is OK.

**Comment by hawkeye64** [comment]
Just install the dependency: `quasar ext add @quasar/colorize` and you are good to go.
