### ISSUE TITLE
Add ability to not render the fullscreen button

### ISSUE THREAD

**Issue by bebekar** [quasarframework/app-extension-qmediaplayer#77]
in many cases we may not require this at all. 
I would prefer to use the qzoom **if required** rather than the browser native.

**Comment by hawkeye64** [comment]
When I am making updates next on QMediaPlayer, I will add thi sfunctionality. Thanks for reporting good ideas! :heart:

**Comment by bebekar** [comment]
Thanks. 
the other would be to allow user to define custom full-screen functionality if possible.

**Comment by hawkeye64** [comment]
How so? You mean let them control the fullscreen themselves?

**Comment by bebekar** [comment]
Yes, 
I then have a choice on the button functionality 
(1) disable full screen 
(2) use native full screen 
(3) to use an alternate like q-zoom 
(4) build ones own to handle the media (say PIP) picture in picture or any other possibility.

**Comment by hawkeye64** [comment]
There is a slot for replacing the fullscreen button. If you do this, then you are responsible for handling the fullscreen actions. You can also call the method `toggleFullscreen()` via a ref or do your own, as you say.
I think this handles your use-case.
