### ISSUE TITLE
Allow Tracks with Sources Type Audio

### ISSUE THREAD

**Issue by wwwizzarrdry** [quasarframework/app-extension-qmediaplayer#8]
Probably a limitation of html5 spec, but is there a way to allow a tracks array when the sources type is audio?

I've got a bunch of lyrics.vtt files that accompany my audio files (mp3, flac, etc) but when I add a tracks array (type: 'subtitles') the player breaks.

Is there no way to allow subtitles for audio?

**Comment by hawkeye64** [comment]
Apologies for not noticing this earlier. Where there is a will, there is always a way. I am not sure if HTML5 Audio supports text, like lyrics, but I doubt it. The intention was that any dev can combine the app with a picture above (maybe album cover) and if lyrics are desired, then get the time from the player. match the lyrics file,  and display it.

Currently, I am maintaining a lot and don't have time to even do up an example for this.

Is this something really, really needed? Some business decision behind it?

**Comment by wwwizzarrdry** [comment]
No, just wondering if it's an issue with the component or the html5 spec.

**Comment by hawkeye64** [comment]
spec
