### ISSUE TITLE
Fallback for unsupported video urls

### ISSUE THREAD

**Issue by wwwizzarrdry** [quasarframework/app-extension-qmediaplayer#9]
It would be nice to fallback to Qvideo if video source is unsupported, such as in the case of YouTube videos. Right now, QMediaPlayer requires a lot of babysitting via regex and helper functions to switch between QVideo and QMediaPlayer based on the video source.

Basically, if the provided source and type are unsupported, we need to fallback to an alternative player that can handle the stream.

**Comment by hawkeye64** [comment]
I hope to, eventually, add Youtube and Vimeo support.

**Comment by wwwizzarrdry** [comment]
In the meantime, I think by adding a url whitelist to the component, we could easily default to the appropriate player based on the src prop.

**Comment by hawkeye64** [comment]
I'm not quite sure what you mean by "url whitelist"

**Comment by hawkeye64** [comment]
Closing this for now.
